### ISSUE TITLE
SetState Not working 

### ISSUE THREAD

**Issue by Mahan3340** [mattprecious/swirl#6] opened 2017-08-26 07:25 UTC
Hi , using this on android 7.1.1 nexus 5x , and set state does nothing and there's just a white blank view 
, I've set the style and colors and when I use attr to set state its showing in Design mode but when running its again an blank view and setting state wont work 

`    <com.mattprecious.swirl.SwirlView
                android:id="@+id/fingerprint_dialog_fingerprint_image"
                style="@style/Finger"
                android:layout_width="60dp"
                android:layout_height="60dp"
                android:layout_gravity="center"
                app:swirl_state="error"/>`

` <style name="Finger" parent="Theme.AppCompat">
        <item name="swirl_ridgeColor">@color/sh</item>
        <item name="swirl_errorColor">@color/red</item>
    </style>`

** I've also set the colors in myAppThemeStyle , not result

**Comment by mattprecious** [comment] 2017-08-31 21:26
Does the sample app in this repository work for you? I suggest taking a look at that to possibly see what you're missing.

**Comment by commonsguy** [comment] 2018-01-15 21:40
I can reproduce the reported problem here, using `1.0.0`, tested on a Nexus 5X running Android 8.1, with the sample app from the repo.

AFAICT, this is working as intended, as the animated GIF on the project home page suggests that the "off" state is blank. I hadn't understood that from the GIF; it was only after running into this problem in an app, then trying the sample app, did I see how the GIF matches the app output.

Here are the screenshots from the sample app:

![swirl1](https://user-images.githubusercontent.com/103772/34962493-e352c348-fa11-11e7-9f70-b63fec3ac183.png)
![swirl2](https://user-images.githubusercontent.com/103772/34962494-e35f5d92-fa11-11e7-85d8-cd862a6bb509.png)
![swirl3](https://user-images.githubusercontent.com/103772/34962495-e369983e-fa11-11e7-9610-ab6c04443622.png)

I guess that I had expected:

- Gray fingerprint icon in the `off` state
- Other color fingerprint icon in the `on` state (e.g., when the fingerprint scanner is active)
- `error` pretty much as implemented

**Comment by mattprecious** [comment] 2018-01-16 18:48
Yeah, what you're seeing is working as intended. I can see the confusion though, since the fingerprint turns green briefly in the GIF before switching to the error state. That's all part of the error animation.

I'm going to close this out until someone can give me repro steps for the original issue.

**Closed as completed by mattprecious** 2018-01-16 18:48 UTC
